'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("frmMain.vb.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bckfu() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bckfu", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property beyondimagination() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beyondimagination", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bloodyhell() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bloodyhell", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property conduithistory() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("conduithistory", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property curedofdel() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("curedofdel", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property dontworry() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("dontworry", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property final_scene_des() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("final_scene_des", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property getoutofthedungeon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("getoutofthedungeon", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property greatmount() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("greatmount", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property guard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hero() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hero", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property honor() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("honor", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ironfistfreedom() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ironfistfreedom", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property itmattersnot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("itmattersnot", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property journeyseeyouwell() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("journeyseeyouwell", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property king() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property merelypb() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("merelypb", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property moral_scene_des() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("moral_scene_des", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property moreeffortintoseers() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("moreeffortintoseers", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property muchlikeabook() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("muchlikeabook", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property negMorKillKing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("negMorKillKing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property negMorNotKillKing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("negMorNotKillKing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property notatyrant() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notatyrant", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property notinnocent() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notinnocent", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property notsavedprisoner() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notsavedprisoner", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ohWhyisthat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ohWhyisthat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property oldasdust() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("oldasdust", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property oldman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oldman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oldmansaiddes() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("oldmansaiddes", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property oldmansoulpower() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("oldmansoulpower", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property payforyourlies() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("payforyourlies", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property placeholding_title() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("placeholding_title", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PosMorKillKing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PosMorKillKing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PosMorNotKillKing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PosMorNotKillKing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property prisoner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prisoner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rldniim() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("rldniim", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property savedprisoner() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("savedprisoner", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property saviorwdum() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("saviorwdum", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property scene1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property scene2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property seersneversaid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("seersneversaid", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sosorry() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sosorry", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property soul_absorbing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("soul_absorbing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property thegroundthrists() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("thegroundthrists", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ulimsavior() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ulimsavior", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ulure() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ulure", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property urbintbs() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("urbintbs", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property what() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("what", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property whereami() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("whereami", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property why() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("why", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property whyshouldkinfall() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("whyshouldkinfall", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property youaretheone() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("youaretheone", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property youratyrant() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("youratyrant", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
